apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/vcsoft/vcsoft/k8s/tallerargocd.git
    targetRevision: HEAD
    directory:
      recurse: true
    path: lab
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-vcsoft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true